#!/bin/bash
VUE3="/home/ec2-user/transform-custom/e-shopping-test7/e-shopping/ecommerce-frontend/vue3-app"
OUT="/home/ec2-user/transform-custom/output_documents/vue"
mkdir -p "$OUT"
cp "$VUE3/final_verification.md" "$OUT/final_verification.md"
cp "$VUE3/dependency-migration.md" "$OUT/dependency-migration.md"
cp "$VUE3/deep-selector-migrations.md" "$OUT/deep-selector-migrations.md"
cp "$VUE3/mixin-to-composable-mapping.md" "$OUT/mixin-to-composable-mapping.md"
cp "$VUE3/vuex-to-pinia-mapping.md" "$OUT/vuex-to-pinia-mapping.md"
cp "$VUE3/filter-to-function-mapping.md" "$OUT/filter-to-function-mapping.md"
cp "$VUE3/event-bus-migration.md" "$OUT/event-bus-migration.md"
cp "$VUE3/migration-progress.txt" "$OUT/migration-progress.md"
echo "All documents copied"
ls -la "$OUT/"
